baseURL = "https://sunls.me/blog/"
theme = "LoveIt"

# ç½‘ç«™æ ‡é¢˜
title = "Thinking and recording"

defaultContentLanguage = "zh-cn"
# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™ ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# è¯­è¨€åç§° ["English", "ç®€ä½“ä¸­æ–‡", "FranÃ§ais", "Polski", ...]
languageName = "ç®€ä½“ä¸­æ–‡"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true

# ä½œè€…é…ç½®
[author]
  name = "sunls"
  email = "liuss.zy@outlook.com"
  link = "https://github.com/sunls24"

# èœå•é…ç½®
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = "ğŸ”–"
    name = "æ–‡ç« "
    url = "/posts/"

 [params.header]
   [params.header.title]
     typeit = false
     # æ ‡é¢˜åç§°
     name = "ğŸ˜´"
  [params.footer]
    hugo = true
    since = 2022
    author = false
  [params.home]
    [params.home.profile]
      enable = true
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "avatar.jpeg"
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜ (å…è®¸ HTML æ ¼å¼)
      subtitle = "Keep It Simple, Stupid"
      # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = true
      # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
      social = true
    [params.home.posts]
      enable = false

  [params.social]
    GitHub = "https://github.com/sunls24"
    Email = "liuss.zy@outlook.com"
  [params.page]
    [params.page.toc]
      # æ˜¯å¦ä½¿ç”¨ç›®å½•
      enable = true
      # LoveIt æ–°å¢ | 0.2.9 æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
      keepStatic = false
      # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
      auto = true
    [params.page.share]
      enable = false
  [params.analytics]
    enable = false

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  # è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false æ˜¯å¿…è¦çš„è®¾ç½® (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
